name: cv_model_lab
description: Cross-platform Flutter Desktop and PWA tool for COCO object detection dataset and model error analysis.
publish_to: none
version: 0.6.1+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.7
  archive: ^4.0.9
  pdf: ^3.10.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
