name: cv_model_lab
description: Cross-platform Flutter Desktop and PWA tool for COCO object detection dataset and model error analysis.
publish_to: none
version: 0.8.0+6

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.3.3
  archive: ^4.0.9
  pdf: ^3.10.8
  http: ^1.2.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/DejaVuSans.ttf
    - assets/fonts/DejaVuSans-Bold.ttf
