"""Parity tests: the Python port must reproduce the Dart EvalResult exactly.

Fixtures are generated by the Dart test
``test/server_parity/generate_fixtures_test.dart`` and committed to
``server/tests/fixtures/``. Regenerate them with:

    flutter test test/server_parity/generate_fixtures_test.dart
"""

from __future__ import annotations

from pathlib import Path

import orjson
import pytest

from cvmlab_server.core import coco_loader, metrics, serialization
from cvmlab_server.core.models import EvalConfig

_REPO_ROOT = Path(__file__).resolve().parents[2]
_FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures"

_TOL = 1e-9


def _fixtures():
    if not _FIXTURES_DIR.exists():
        return []
    return sorted(_FIXTURES_DIR.glob("*.json"))


def _config_from_fixture(raw: dict) -> EvalConfig:
    return EvalConfig(
        iou_threshold=raw["iou_threshold"],
        confidence_threshold=raw["confidence_threshold"],
        class_aware_matching=raw["class_aware_matching"],
        ignore_crowd=raw["ignore_crowd"],
        small_object_mode=raw.get("small_object_mode", "coco"),
    )


def _assert_equal(actual, expected, path: str = "") -> None:
    if isinstance(expected, bool) or isinstance(actual, bool):
        assert actual == expected, f"{path}: {actual!r} != {expected!r}"
    elif isinstance(expected, (int, float)) and isinstance(actual, (int, float)):
        assert abs(actual - expected) <= _TOL + 1e-6 * abs(expected), (
            f"{path}: {actual} != {expected}"
        )
    elif isinstance(expected, dict):
        assert isinstance(actual, dict), f"{path}: expected dict, got {type(actual)}"
        assert set(actual.keys()) == set(expected.keys()), (
            f"{path}: keys {set(actual.keys())} != {set(expected.keys())}"
        )
        for key in expected:
            _assert_equal(actual[key], expected[key], f"{path}.{key}")
    elif isinstance(expected, list):
        assert isinstance(actual, list), f"{path}: expected list, got {type(actual)}"
        assert len(actual) == len(expected), (
            f"{path}: length {len(actual)} != {len(expected)}"
        )
        for index, (a, e) in enumerate(zip(actual, expected)):
            _assert_equal(a, e, f"{path}[{index}]")
    else:
        assert actual == expected, f"{path}: {actual!r} != {expected!r}"


@pytest.mark.skipif(not _fixtures(), reason="parity fixtures not generated")
@pytest.mark.parametrize("fixture_path", _fixtures(), ids=lambda p: p.stem)
def test_eval_parity(fixture_path: Path) -> None:
    fixture = orjson.loads(fixture_path.read_bytes())
    annotations_path = _REPO_ROOT / fixture["source"]["annotations"]
    predictions_path = _REPO_ROOT / fixture["source"]["predictions"]
    config = _config_from_fixture(fixture["config"])

    dataset = coco_loader.load_annotations(annotations_path.read_bytes())
    model_run = coco_loader.load_predictions(
        predictions_path.read_bytes(), dataset, "run", "run"
    )
    result = metrics.evaluate(dataset, model_run, config)
    compact = serialization.eval_result_to_compact_json(result)

    _assert_equal(compact, fixture["expected"])
